### ISSUE TITLE
Case-insensitive

### ISSUE THREAD

**Issue by manuel-rubio** [hayleigh-dot-dev/nibble#5]
Is it possible to indicate tokens to be case-sensitive or case-insensitive? I'm needing for a SQL-like parser to have case-insensitive tokens.

**Comment by manuel-rubio** [comment]
what about this?
```gleam
pub fn itoken(str: String, value: a) -> Matcher(a, mode) {
  use mode, lexeme, _ <- Matcher

  case string.lowercase(lexeme) == string.lowercase(str) {
    True -> Keep(value, mode)
    False -> NoMatch
  }
}
```

**Comment by manuel-rubio** [comment]
Any advance regarding this?

**Comment by hayleigh-dot-dev** [comment]
The api lets you define custom matchers for a reason! Your custom matcher seems fine if it works for you. Unfortunately all my spare time is spent maintaining other packages, if I have the time and energy to work on nibble it will be to improve the (very lacking) docs at this point!
